version: "3.8"

services:
    homeassistant:
        container_name: homeassistant
        image: ghcr.io/home-assistant/home-assistant:stable
        restart: unless-stopped
        volumes:
            - ./homeassistant/config:/config
            - /etc/localtime:/etc/localtime:ro
        network_mode: host # Required for device discovery (mDNS/UPnP)
        environment:
            - TZ=Australia/Melbourne
        depends_on:
            - mosquitto
            - matter-server
            - zigbee2mqtt
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"

    zigbee2mqtt:
        container_name: zigbee2mqtt
        image: koenkk/zigbee2mqtt:latest
        restart: unless-stopped
        ports:
            - "8080:8080" # Frontend UI
        volumes:
            - ./zigbee2mqtt/data:/app/data
            - /run/udev:/run/udev:ro
        environment:
            - TZ=Australia/Melbourne
        devices:
            # Change this path to match your specific Zigbee coordinator
            - /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231216183709-if00:/dev/ttyACM0
        depends_on:
            - mosquitto

    matter-server:
        container_name: matter-server
        image: ghcr.io/home-assistant-libs/python-matter-server:stable
        restart: unless-stopped
        security_opt:
            - apparmor=unconfined
        cap_add:
            - NET_ADMIN
            - NET_RAW
        environment:
            - TZ=Australia/Melbourne
        network_mode: host
        security_opt:
          # Needed for Bluetooth via dbus
          - apparmor:unconfined
        ipc: host # Allows shared socket memory access
        volumes:
            - ./matter-data:/data
            - /run/dbus:/run/dbus:ro
            - /var/run/dbus:/var/run/dbus:ro # Added legacy socket path ma
        command: --storage-path /data --paa-root-cert-dir /data/credentials --bluetooth-adapter 0 --primary-interface eno1

    mosquitto:
        container_name: mosquitto
        image: eclipse-mosquitto:latest
        restart: unless-stopped
        environment:
            - TZ=Australia/Melbourne
        ports:
            - "1883:1883"
            - "9001:9001"
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - ./mosquitto/data:/mosquitto/data
            - ./mosquitto/log:/mosquitto/log
