version: "3.2"

networks:
    homelab:
        external: true

services:
    prowlarr:
        image: ghcr.io/linuxserver/prowlarr:develop
        container_name: prowlarr
        hostname: prowlarr
        networks:
            - homelab
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
        ports:
            - 9696:9696 #prowlarr
        volumes:
            - ./prowlarr:/config
        restart: "always" # no | always | on-failure | unless--stopped
        logging:
            driver: json-file

    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        hostname: flaresolverr
        networks:
            - homelab
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=Australia/Melbourne
        ports:
            - 8191:8191
        restart: unless-stopped

    sonarr:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        hostname: sonarr
        networks:
            - homelab
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
            #- UMASK=002
        ports:
            - 8989:8989 #sonarr
        volumes:
            - ./sonarr:/config
            - /data:/data
            - /data/torrents:/downloads
        restart: "always" # no | always | on-failure | unless--stopped
        logging:
            driver: json-file

    radarr:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        hostname: radarr
        networks:
            - homelab
        ports:
            - 7878:7878
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
            #- UMASK=002
        volumes:
            - ./radarr:/config
            - /data:/data
            - /data/torrents:/downloads
        restart: "always" # no | always | on-failure | unless--stopped
        logging:
            driver: json-file

    lidarr:
        image: ghcr.io/linuxserver/lidarr
        container_name: lidarr
        hostname: lidarr
        networks:
            - homelab
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
        ports:
            - 8686:8686 #lidarr
        volumes:
            - ./lidarr:/config
            - /data:/data
        restart: "always" # no | always | on-failure | unless--stopped
        logging:
            driver: json-file

    readarr:
        image: lscr.io/linuxserver/readarr:develop
        container_name: readarr
        hostname: readarr
        networks:
            - homelab
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
        ports:
            - 8787:8787 #readarr
        volumes:
            - ./readarr:/config
            - /data:/data
        restart: "always" # no | always | on-failure | unless--stopped
        logging:
            driver: json-file
        # m4b-tool: # use the alias tool    https://github.com/sandreas/m4b-tool#docker

    bazarr:
        container_name: bazarr
        image: ghcr.io/hotio/bazarr:latest
        ports:
            - 6767:6767
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Europe/Amsterdam
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /docker/appdata/bazarr:/config
            - /data/media:/data/media
        restart: "always"
        logging:
            driver: json-file

    sabnzb:
        image: lscr.io/linuxserver/sabnzbd:latest
        container_name: sabnzb
        ports:
            - 8090:8080
        logging:
            driver: json-file
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
        volumes:
            - ./sabnzb:/config
            - /data/torrents:/data/torrents
        restart: "always" # no | always | on-failure | unless--stopped

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        networks:
            - homelab
        ports:
            - 8091:8080
            - 8180:8180
            - 6881:6881
            - 6881:6881/udp
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
            - WEBUI_PORT=8180
        volumes:
            - ./qbittorrent:/config
            - /data/torrents:/downloads
        restart: unless-stopped # no | always | on-failure | unless-stopped
