version: "3.8"

networks:
    homelab:
        external: true

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
    wireguard:
        image: linuxserver/wireguard
        container_name: wireguard
        cap_add:
            - NET_ADMIN
            - SYS_MODULE
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Australia/Melbourne
            - SERVERURL=carnegie.tplinkdns.com #optional | Ip or domain of your server
            - SERVERPORT=51820 #optional
            - PEERS=10 #optional
            - PEERDNS=auto #optional
            - INTERNAL_SUBNET=10.100.13.0 #optional
            - ALLOWEDIPS=0.0.0.0/0 #optional
            - LOG_CONFS=true #optional
        volumes:
            - ./config/wireguard:/config
            - /lib/modules:/lib/modules
            - /usr/src:/usr/src
        ports:
            - 51820:51820/udp
              #- 8180:8180 #qbittorrent
              #- 6881:6881 #qbittorrent
              #- 6881:6881/udp #qbittorrent
              #- 8280:8280 #sabnzb
              #- 7878:7878 #radarr
        sysctls:
            - net.ipv4.conf.all.src_valid_mark=1
        dns:
            - 172.18.0.2
        restart: unless-stopped
        networks:
            homelab:
                ipv4_address: 172.18.0.3
